Propagates flat pair read noises to ptcDataset
lsst/ip_isr pull request #295
Opened 2024-01-17 21:47 UTC by Alex-Broughton

2024-01-20 00:14 UTC, youtsumi approved these changes

2024-01-23 23:18 UTC, czwa requested changes
I think DM-42163 will merge first, so this should increment the version again.

2024-01-23 23:18 UTC, czwa commented on python/lsst/ip/isr/ptcDataset.py
> +    _VERSION = 1.6
This may be 1.7 now.  I know there's another ticket in flight that has changed the version to 1.6: DM-42163.

2024-01-29 21:44 UTC, czwa commented
General comment applicable here and elsewhere: PR names should start with the ticket name, so they're easier to track: https://developer.lsst.io/work/flow.html#make-a-pull-request

2024-01-29 21:52 UTC, czwa approved these changes
Can you add an entry to the unit tests to check existence and type?  This line is the similar change on the previous ticket, and as `ci_cpp`'s testing is intentionally broken for the sprint, this will at least provide something for Jenkins to check:
https://github.com/lsst/ip_isr/blob/main/tests/test_ptcDataset.py#L90
Approving this on condition a matching line is added for `noiseList`.

2024-02-02 01:41 UTC, merged