DM-46509: Add FULLCOVRIANCE_NO_B fit option to PTC solver
lsst/ip_isr pull request #354
Opened 2024-10-15 00:12 UTC by Alex-Broughton

2024-10-15 16:22 UTC, erykoff requested changes
If we read an old PTC, we still want to fill in the noB parameters so they are available to the user, but any access will issue a deprecation warning.  So I think this went too far in the code removal

2024-10-31 17:50 UTC, erykoff commented
My comment above is still a problem.  If the file has these columns we want to read them in; when that is done it shouldn't issue a deprecation warning, but if you try to access them it will (but will have values!)

2024-11-04 18:45 UTC, erykoff reviewed
A couple more comments.  Also I want to make sure that when you run tests that no warnings from this deprecation are emitted, either here or on cp_pipe.

2024-11-04 18:45 UTC, erykoff commented on python/lsst/ip/isr/ptcDataset.py
> +                inDict['aMatrixNoB'][ampName] = np.full_like(inDict['aMatrix'][ampName], np.nan)
I don't know if this else is necessary.  For newer PTCs we shouldn't be using these fields at all, right?

2024-11-04 18:45 UTC, erykoff commented on python/lsst/ip/isr/ptcDataset.py
> +                partialPtc._covariancesModelNoB[ampName].ravel()
We aren't using this at all; I think if we need filler this should be explicitly filled with nans.

2024-11-15 16:30 UTC, erykoff commented on python/lsst/ip/isr/ptcDataset.py
> +            # )
Remove this?

2024-11-15 16:31 UTC, erykoff commented on python/lsst/ip/isr/ptcDataset.py
> +
This needs the TODO ticket link

2024-11-15 16:45 UTC, TallJimbo commented on python/lsst/ip/isr/ptcDataset.py
> +        adu^2). Will be deprecated in v28.
I think our deprecation messages typically only say "after", not "before", and if this deprecation is going in now then removal is "after v29."

2024-11-17 22:41 UTC, erykoff commented on python/lsst/ip/isr/ptcDataset.py
> +        adu^2). Will be deprecated in v28.
This still needs to be fixed!

2024-11-17 22:46 UTC, Alex-Broughton commented on python/lsst/ip/isr/ptcDataset.py
> +        inDict['aMatrixNoB'] = dict()
Hang on... Jenkins is failing when I take these out. I think we still need these to read in older versions of the PTC.

2024-11-17 23:19 UTC, erykoff commented on python/lsst/ip/isr/ptcDataset.py
> +        inDict['aMatrixNoB'] = dict()
You either need an `else` after line 822 (current version), filling with nans, or an else after line 566 filling with nans.  Second one is what I recommend as it's more general.

2024-11-18 13:28 UTC, erykoff commented on python/lsst/ip/isr/ptcDataset.py
> +        Will be deprecated after v29.
Will be  *removed* (and the others)

2024-11-19 20:47 UTC, erykoff approved these changes

2024-11-19 21:16 UTC, merged