DM-45928: add parallel CTI and add serial/parallel turnoff calculations to DeferredChargeCalib
lsst/ip_isr pull request #360
Opened 2024-11-06 16:51 UTC by Alex-Broughton

2025-01-15 22:25 UTC, czwa approved these changes
Minor comments.

2025-01-15 22:25 UTC, czwa commented on python/lsst/ip/isr/deferredCharge.py
> +            inDict['signals'] = {amp: value for amp, value in zip(amps, signals)}
Another "it must work if the tests pass", but: does this round-trip correctly?

2025-01-15 22:25 UTC, czwa commented on python/lsst/ip/isr/deferredCharge.py
> +        if calibVersion < 1.2:
`elif` here?

2025-01-15 22:25 UTC, czwa commented on tests/test_deferredCharge.py
> +        self.calib.parallelCtiTurnoffSamplingErr['amp1'] = 1.0e3
After reading through the rest, I think this probably should be fixed here (so `amp1` gets a `logistic` trap).  Adding a `testPartiallyPopulated` might be good to add to test that `serialTraps` can be not populated for `amp1` to keep the accidental test case intact.

2025-01-15 23:39 UTC, czwa commented
Talking with @erykoff let me know that this is going back for more development, so feel free to ignore my comments as needed.

2025-01-30 17:34 UTC, erykoff commented on python/lsst/ip/isr/deferredCharge.py
> +        A dictionary, keyed by amplifier name, of the serial EPER
Can you spell out EPER at least once in the docstring?

2025-01-30 17:34 UTC, erykoff commented on python/lsst/ip/isr/isrStatistics.py
> +            parallelOverscanResults=None, **kwargs):
Do we use the parallelOverscanResults anywhere?  Is this just adding this in case we need it in the future?

2025-01-30 17:34 UTC, erykoff commented on python/lsst/ip/isr/isrStatistics.py
> +
Please remove debug checks.

2025-01-30 17:34 UTC, erykoff commented on python/lsst/ip/isr/isrStatistics.py
> +                    dataRegion = image[amp.getBBox()]
I don't think this is correct (or could be wrong depending on configs).  The `image` in this case (potentially) has bias/dark/flat/bfk/etc applied (though this is a pipeline choice).  Can't you just use the untrimmed image exclusively and ignore the trimmed image for the CTI statistics?  The untrimmed image has the same operations guaranteed to be applied to both the overscan and imaging regions, and therefore will be matched.  Plus, I think it would make the code simpler.

2025-01-30 17:34 UTC, erykoff commented on python/lsst/ip/isr/isrStatistics.py
> +                    nParallelOverscanRows = amp.getRawParallelOverscanBBox().getHeight()
Note that these are only going to work with an "LSST style" camera, which is fine, that's what we support.

2025-01-30 17:34 UTC, erykoff commented on python/lsst/ip/isr/isrStatistics.py
> +                    nParallelOverscanRows = amp.getRawParallelOverscanBBox().getHeight()
(The problem is that a different camera could have a different row/col orientation and width/height would therefore be reversed).

2025-01-30 17:34 UTC, erykoff commented on python/lsst/ip/isr/isrTask.py
> +                                                 parallelOverscanResults=[None for _ in overscans],
The parallelOverscanResults could/should just be None here (but as asked above this seems to be unused anyway).

2025-01-30 17:34 UTC, erykoff commented on python/lsst/ip/isr/isrTaskLSST.py
> +        if self.config.doCalculateStatistics:
Is this the right check?  It's not if we're calculating statistics at all, it's if we're computing CTI statistics.  As this is written we're going to be doing an expensive clone operation for regular ISR which we do not want.  So we want to check if we're doing cti statistics, `self.config.isrStatistics.doCtiStatistics` (I think?) and if not set `untrimmedCcdExposure = None` to protect it below.

2025-01-30 19:00 UTC, Alex-Broughton commented on python/lsst/ip/isr/deferredCharge.py
> +            inDict['signals'] = {amp: value for amp, value in zip(amps, signals)}
Can you clarify what you mean by round-trip?

2025-01-30 19:01 UTC, erykoff commented on python/lsst/ip/isr/deferredCharge.py
> +            inDict['signals'] = {amp: value for amp, value in zip(amps, signals)}
There does appear to be a test (but is it too trivial?) that you can serialize to fits and read it back.

2025-01-30 19:03 UTC, Alex-Broughton commented on python/lsst/ip/isr/isrStatistics.py
> +            parallelOverscanResults=None, **kwargs):
No, not yet. I wasn't sure if we wanted to include parallel CTI statistics in the ISR statistics output dataset in the future.

2025-01-31 16:42 UTC, Alex-Broughton commented on python/lsst/ip/isr/isrStatistics.py
> +                    dataRegion = image[amp.getBBox()]
We could, but the defect mask would not be applied to the untrimmed image, so we would calculate CTI statistics on an image with potentially large defects (that might affect the last imaging pixels or overscan). When I calculate the statistics I use median of the last imaging column (serial) or row (parallel), so it might be pretty robust against not masking defects. I can go ahead and simplify it, but we should check the calibration or add a test to cp_verify in the future that can make sure there are no defects impacting the CTI solver.

2025-01-31 17:02 UTC, erykoff commented on python/lsst/ip/isr/isrStatistics.py
> +                    dataRegion = image[amp.getBBox()]
Ah!  That is a great point, you are correct.  This should be made clear in the code comments, and we need to be extra careful about our pipeline settings.

2025-01-31 22:59 UTC, czwa requested changes
I think I'm generally happy, except for the serial trap handling in `test_deferredCharge.py`.

2025-02-03 17:17 UTC, erykoff approved these changes
A couple of remaining small documentation requests; otherwise looks great!

2025-02-03 17:17 UTC, erykoff commented on python/lsst/ip/isr/isrStatistics.py
> +            from IsrTask.
Can you file this deprecate ticket and link it here?  It would need an RFC to be done, but we can file the plan now.

2025-02-03 17:17 UTC, erykoff commented on python/lsst/ip/isr/isrStatistics.py
> +            The exposure to measure.
Can you add a comment here that the full exposure is needed because the data region has the defect mask?

2025-02-03 17:17 UTC, erykoff commented on python/lsst/ip/isr/isrStatistics.py
> +        self.log.warning("Using the legacy version of CTI statistics may give wrong CTI")
Do we need a warning here and above?  (Though heck why not, nobody should be running this...)

2025-02-03 23:46 UTC, czwa approved these changes

2025-02-04 00:56 UTC, merged